-- Vhdl model created from schematic lab3.sch - Mon Aug 30 19:04:33 2004

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;
-- synopsys translate_off
LIBRARY UNISIM;
USE UNISIM.Vcomponents.ALL;
-- synopsys translate_on

ENTITY lab3 IS
   PORT ( C1	:	IN	STD_LOGIC; 
          C2	:	IN	STD_LOGIC; 
          C3	:	IN	STD_LOGIC; 
          C4	:	IN	STD_LOGIC; 
          R1	:	IN	STD_LOGIC; 
          R2	:	IN	STD_LOGIC; 
          R3	:	IN	STD_LOGIC; 
          R4	:	IN	STD_LOGIC; 
          A	:	OUT	STD_LOGIC; 
          B	:	OUT	STD_LOGIC; 
          C	:	OUT	STD_LOGIC; 
          D	:	OUT	STD_LOGIC; 
          Dv	:	OUT	STD_LOGIC);

end lab3;

ARCHITECTURE SCHEMATIC OF lab3 IS
   SIGNAL A_DUMMY	:	STD_LOGIC;
   SIGNAL B_DUMMY	:	STD_LOGIC;
   SIGNAL C_DUMMY	:	STD_LOGIC;
   SIGNAL D_DUMMY	:	STD_LOGIC;
   SIGNAL XLXN_52	:	STD_LOGIC;
   SIGNAL XLXN_53	:	STD_LOGIC;
   SIGNAL XLXN_55	:	STD_LOGIC;
   SIGNAL XLXN_57	:	STD_LOGIC;
   SIGNAL XLXN_61	:	STD_LOGIC;
   SIGNAL XLXN_63	:	STD_LOGIC;
   SIGNAL XLXN_66	:	STD_LOGIC;
   SIGNAL XLXN_71	:	STD_LOGIC;
   SIGNAL XLXN_74	:	STD_LOGIC;
   SIGNAL XLXN_75	:	STD_LOGIC;
   SIGNAL XLXN_77	:	STD_LOGIC;
   SIGNAL XLXN_78	:	STD_LOGIC;
   SIGNAL XLXN_81	:	STD_LOGIC;
   SIGNAL XLXN_82	:	STD_LOGIC;
   SIGNAL XLXN_85	:	STD_LOGIC;
   SIGNAL XLXN_86	:	STD_LOGIC;
   SIGNAL XLXN_87	:	STD_LOGIC;
   SIGNAL XLXN_88	:	STD_LOGIC;
   SIGNAL XLXN_89	:	STD_LOGIC;
   SIGNAL XLXN_90	:	STD_LOGIC;
   SIGNAL XLXN_91	:	STD_LOGIC;
   SIGNAL XLXN_92	:	STD_LOGIC;
   SIGNAL XLXN_93	:	STD_LOGIC;
   SIGNAL XLXN_94	:	STD_LOGIC;
   SIGNAL XLXN_95	:	STD_LOGIC;
   SIGNAL XLXN_96	:	STD_LOGIC;
   SIGNAL XLXN_97	:	STD_LOGIC;

   ATTRIBUTE BOX_TYPE : STRING;

   COMPONENT AND2
      PORT ( I0	:	IN	STD_LOGIC; 
             I1	:	IN	STD_LOGIC; 
             O	:	OUT	STD_LOGIC);
   END COMPONENT;

   ATTRIBUTE BOX_TYPE OF AND2 : COMPONENT IS "BLACK_BOX";
   COMPONENT OR2
      PORT ( I0	:	IN	STD_LOGIC; 
             I1	:	IN	STD_LOGIC; 
             O	:	OUT	STD_LOGIC);
   END COMPONENT;

   ATTRIBUTE BOX_TYPE OF OR2 : COMPONENT IS "BLACK_BOX";
   COMPONENT OR3
      PORT ( I0	:	IN	STD_LOGIC; 
             I1	:	IN	STD_LOGIC; 
             I2	:	IN	STD_LOGIC; 
             O	:	OUT	STD_LOGIC);
   END COMPONENT;

   ATTRIBUTE BOX_TYPE OF OR3 : COMPONENT IS "BLACK_BOX";
   COMPONENT OR4
      PORT ( I0	:	IN	STD_LOGIC; 
             I1	:	IN	STD_LOGIC; 
             I2	:	IN	STD_LOGIC; 
             I3	:	IN	STD_LOGIC; 
             O	:	OUT	STD_LOGIC);
   END COMPONENT;

   ATTRIBUTE BOX_TYPE OF OR4 : COMPONENT IS "BLACK_BOX";
   COMPONENT OR5
      PORT ( I0	:	IN	STD_LOGIC; 
             I1	:	IN	STD_LOGIC; 
             I2	:	IN	STD_LOGIC; 
             I3	:	IN	STD_LOGIC; 
             I4	:	IN	STD_LOGIC; 
             O	:	OUT	STD_LOGIC);
   END COMPONENT;

   ATTRIBUTE BOX_TYPE OF OR5 : COMPONENT IS "BLACK_BOX";
BEGIN
   A <= A_DUMMY;
   B <= B_DUMMY;
   C <= C_DUMMY;
   D <= D_DUMMY;

   XLXI_19 : AND2
      PORT MAP (I0=>R4, I1=>C4, O=>XLXN_82);

   XLXI_18 : AND2
      PORT MAP (I0=>R4, I1=>C3, O=>XLXN_81);

   XLXI_17 : AND2
      PORT MAP (I0=>R4, I1=>C2, O=>open);

   XLXI_16 : AND2
      PORT MAP (I0=>R4, I1=>C1, O=>XLXN_78);

   XLXI_15 : AND2
      PORT MAP (I0=>R3, I1=>C4, O=>XLXN_77);

   XLXI_14 : AND2
      PORT MAP (I0=>R3, I1=>C3, O=>XLXN_75);

   XLXI_13 : AND2
      PORT MAP (I0=>R3, I1=>C2, O=>XLXN_74);

   XLXI_9 : AND2
      PORT MAP (I0=>R3, I1=>C1, O=>XLXN_92);

   XLXI_8 : AND2
      PORT MAP (I0=>R2, I1=>C4, O=>XLXN_71);

   XLXI_7 : AND2
      PORT MAP (I0=>R2, I1=>C3, O=>XLXN_66);

   XLXI_6 : AND2
      PORT MAP (I0=>R2, I1=>C2, O=>XLXN_63);

   XLXI_5 : AND2
      PORT MAP (I0=>R2, I1=>C1, O=>XLXN_61);

   XLXI_4 : AND2
      PORT MAP (I0=>R1, I1=>C4, O=>XLXN_57);

   XLXI_3 : AND2
      PORT MAP (I0=>R1, I1=>C3, O=>XLXN_55);

   XLXI_2 : AND2
      PORT MAP (I0=>R1, I1=>C2, O=>XLXN_53);

   XLXI_1 : AND2
      PORT MAP (I0=>R1, I1=>C1, O=>XLXN_52);

   XLXI_31 : OR2
      PORT MAP (I0=>XLXN_82, I1=>XLXN_81, O=>XLXN_97);

   XLXI_30 : OR2
      PORT MAP (I0=>XLXN_81, I1=>XLXN_78, O=>XLXN_93);

   XLXI_27 : OR2
      PORT MAP (I0=>XLXN_75, I1=>XLXN_92, O=>XLXN_96);

   XLXI_26 : OR2
      PORT MAP (I0=>XLXN_77, I1=>XLXN_92, O=>XLXN_88);

   XLXI_24 : OR2
      PORT MAP (I0=>XLXN_71, I1=>XLXN_63, O=>XLXN_95);

   XLXI_23 : OR2
      PORT MAP (I0=>XLXN_71, I1=>XLXN_66, O=>XLXN_91);

   XLXI_20 : OR2
      PORT MAP (I0=>XLXN_55, I1=>XLXN_52, O=>XLXN_94);

   XLXI_25 : OR3
      PORT MAP (I0=>XLXN_77, I1=>XLXN_75, I2=>XLXN_74, O=>XLXN_85);

   XLXI_22 : OR3
      PORT MAP (I0=>XLXN_66, I1=>XLXN_63, I2=>XLXN_61, O=>XLXN_87);

   XLXI_28 : OR3
      PORT MAP (I0=>XLXN_82, I1=>XLXN_81, I2=>XLXN_78, O=>XLXN_86);

   XLXI_29 : OR3
      PORT MAP (I0=>XLXN_82, I1=>XLXN_81, I2=>XLXN_78, O=>XLXN_89);

   XLXI_21 : OR3
      PORT MAP (I0=>XLXN_57, I1=>XLXN_55, I2=>XLXN_53, O=>XLXN_90);

   XLXI_33 : OR3
      PORT MAP (I0=>XLXN_89, I1=>XLXN_88, I2=>XLXN_87, O=>B_DUMMY);

   XLXI_32 : OR4
      PORT MAP (I0=>XLXN_86, I1=>XLXN_85, I2=>XLXN_71, I3=>XLXN_57, O=>A_DUMMY);

   XLXI_34 : OR4
      PORT MAP (I0=>XLXN_93, I1=>XLXN_92, I2=>XLXN_91, I3=>XLXN_90, O=>C_DUMMY);

   XLXI_35 : OR4
      PORT MAP (I0=>XLXN_97, I1=>XLXN_96, I2=>XLXN_95, I3=>XLXN_94, O=>D_DUMMY);

   XLXI_42 : OR5
      PORT MAP (I0=>R4, I1=>D_DUMMY, I2=>C_DUMMY, I3=>B_DUMMY, I4=>A_DUMMY,
      O=>Dv);

END SCHEMATIC;



