-- Vhdl model created from schematic sevensegdec.sch - Mon Sep 27 12:09:53 2004

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;
-- synopsys translate_off
LIBRARY UNISIM;
USE UNISIM.Vcomponents.ALL;
-- synopsys translate_on

ENTITY sevensegdec IS
   PORT ( EN	:	IN	STD_LOGIC; 
          SW1	:	IN	STD_LOGIC; 
          SW2	:	IN	STD_LOGIC; 
          SW3	:	IN	STD_LOGIC; 
          SW4	:	IN	STD_LOGIC; 
          A	:	OUT	STD_LOGIC; 
          B	:	OUT	STD_LOGIC; 
          C	:	OUT	STD_LOGIC; 
          D	:	OUT	STD_LOGIC; 
          E	:	OUT	STD_LOGIC; 
          F	:	OUT	STD_LOGIC; 
          G	:	OUT	STD_LOGIC);
   ATTRIBUTE LOC : STRING ;
   ATTRIBUTE LOC OF A : SIGNAL IS "AA13";
   ATTRIBUTE LOC OF B : SIGNAL IS "Y13";
   ATTRIBUTE LOC OF C : SIGNAL IS "Y18";
   ATTRIBUTE LOC OF D : SIGNAL IS "AA20";
   ATTRIBUTE LOC OF E : SIGNAL IS "W18";
   ATTRIBUTE LOC OF F : SIGNAL IS "W13";
   ATTRIBUTE LOC OF G : SIGNAL IS "AB13";

end sevensegdec;

ARCHITECTURE SCHEMATIC OF sevensegdec IS
   SIGNAL XLXN_1	:	STD_LOGIC;
   SIGNAL XLXN_10	:	STD_LOGIC;
   SIGNAL XLXN_100	:	STD_LOGIC;
   SIGNAL XLXN_101	:	STD_LOGIC;
   SIGNAL XLXN_102	:	STD_LOGIC;
   SIGNAL XLXN_103	:	STD_LOGIC;
   SIGNAL XLXN_11	:	STD_LOGIC;
   SIGNAL XLXN_110	:	STD_LOGIC;
   SIGNAL XLXN_111	:	STD_LOGIC;
   SIGNAL XLXN_113	:	STD_LOGIC;
   SIGNAL XLXN_116	:	STD_LOGIC;
   SIGNAL XLXN_117	:	STD_LOGIC;
   SIGNAL XLXN_119	:	STD_LOGIC;
   SIGNAL XLXN_12	:	STD_LOGIC;
   SIGNAL XLXN_121	:	STD_LOGIC;
   SIGNAL XLXN_122	:	STD_LOGIC;
   SIGNAL XLXN_126	:	STD_LOGIC;
   SIGNAL XLXN_127	:	STD_LOGIC;
   SIGNAL XLXN_128	:	STD_LOGIC;
   SIGNAL XLXN_13	:	STD_LOGIC;
   SIGNAL XLXN_132	:	STD_LOGIC;
   SIGNAL XLXN_133	:	STD_LOGIC;
   SIGNAL XLXN_134	:	STD_LOGIC;
   SIGNAL XLXN_14	:	STD_LOGIC;
   SIGNAL XLXN_140	:	STD_LOGIC;
   SIGNAL XLXN_15	:	STD_LOGIC;
   SIGNAL XLXN_16	:	STD_LOGIC;
   SIGNAL XLXN_17	:	STD_LOGIC;
   SIGNAL XLXN_171	:	STD_LOGIC;
   SIGNAL XLXN_18	:	STD_LOGIC;
   SIGNAL XLXN_187	:	STD_LOGIC;
   SIGNAL XLXN_189	:	STD_LOGIC;
   SIGNAL XLXN_19	:	STD_LOGIC;
   SIGNAL XLXN_193	:	STD_LOGIC;
   SIGNAL XLXN_195	:	STD_LOGIC;
   SIGNAL XLXN_197	:	STD_LOGIC;
   SIGNAL XLXN_199	:	STD_LOGIC;
   SIGNAL XLXN_2	:	STD_LOGIC;
   SIGNAL XLXN_20	:	STD_LOGIC;
   SIGNAL XLXN_201	:	STD_LOGIC;
   SIGNAL XLXN_21	:	STD_LOGIC;
   SIGNAL XLXN_22	:	STD_LOGIC;
   SIGNAL XLXN_23	:	STD_LOGIC;
   SIGNAL XLXN_24	:	STD_LOGIC;
   SIGNAL XLXN_25	:	STD_LOGIC;
   SIGNAL XLXN_26	:	STD_LOGIC;
   SIGNAL XLXN_3	:	STD_LOGIC;
   SIGNAL XLXN_4	:	STD_LOGIC;
   SIGNAL XLXN_41	:	STD_LOGIC;
   SIGNAL XLXN_47	:	STD_LOGIC;
   SIGNAL XLXN_49	:	STD_LOGIC;
   SIGNAL XLXN_5	:	STD_LOGIC;
   SIGNAL XLXN_51	:	STD_LOGIC;
   SIGNAL XLXN_54	:	STD_LOGIC;
   SIGNAL XLXN_56	:	STD_LOGIC;
   SIGNAL XLXN_57	:	STD_LOGIC;
   SIGNAL XLXN_58	:	STD_LOGIC;
   SIGNAL XLXN_6	:	STD_LOGIC;
   SIGNAL XLXN_7	:	STD_LOGIC;
   SIGNAL XLXN_73	:	STD_LOGIC;
   SIGNAL XLXN_75	:	STD_LOGIC;
   SIGNAL XLXN_76	:	STD_LOGIC;
   SIGNAL XLXN_77	:	STD_LOGIC;
   SIGNAL XLXN_79	:	STD_LOGIC;
   SIGNAL XLXN_8	:	STD_LOGIC;
   SIGNAL XLXN_80	:	STD_LOGIC;
   SIGNAL XLXN_82	:	STD_LOGIC;
   SIGNAL XLXN_83	:	STD_LOGIC;
   SIGNAL XLXN_84	:	STD_LOGIC;
   SIGNAL XLXN_86	:	STD_LOGIC;
   SIGNAL XLXN_87	:	STD_LOGIC;
   SIGNAL XLXN_89	:	STD_LOGIC;
   SIGNAL XLXN_9	:	STD_LOGIC;
   SIGNAL XLXN_90	:	STD_LOGIC;
   SIGNAL XLXN_91	:	STD_LOGIC;
   SIGNAL XLXN_92	:	STD_LOGIC;
   SIGNAL XLXN_93	:	STD_LOGIC;
   SIGNAL XLXN_94	:	STD_LOGIC;
   SIGNAL XLXN_96	:	STD_LOGIC;
   SIGNAL XLXN_97	:	STD_LOGIC;
   SIGNAL XLXN_98	:	STD_LOGIC;
   SIGNAL XLXN_99	:	STD_LOGIC;

   ATTRIBUTE BOX_TYPE : STRING;

   COMPONENT AND2
      PORT ( I0	:	IN	STD_LOGIC; 
             I1	:	IN	STD_LOGIC; 
             O	:	OUT	STD_LOGIC);
   END COMPONENT;

   ATTRIBUTE BOX_TYPE OF AND2 : COMPONENT IS "BLACK_BOX";
   COMPONENT AND3
      PORT ( I0	:	IN	STD_LOGIC; 
             I1	:	IN	STD_LOGIC; 
             I2	:	IN	STD_LOGIC; 
             O	:	OUT	STD_LOGIC);
   END COMPONENT;

   ATTRIBUTE BOX_TYPE OF AND3 : COMPONENT IS "BLACK_BOX";
   COMPONENT AND4
      PORT ( I0	:	IN	STD_LOGIC; 
             I1	:	IN	STD_LOGIC; 
             I2	:	IN	STD_LOGIC; 
             I3	:	IN	STD_LOGIC; 
             O	:	OUT	STD_LOGIC);
   END COMPONENT;

   ATTRIBUTE BOX_TYPE OF AND4 : COMPONENT IS "BLACK_BOX";
   COMPONENT AND5
      PORT ( I0	:	IN	STD_LOGIC; 
             I1	:	IN	STD_LOGIC; 
             I2	:	IN	STD_LOGIC; 
             I3	:	IN	STD_LOGIC; 
             I4	:	IN	STD_LOGIC; 
             O	:	OUT	STD_LOGIC);
   END COMPONENT;

   ATTRIBUTE BOX_TYPE OF AND5 : COMPONENT IS "BLACK_BOX";
   COMPONENT INV
      PORT ( I	:	IN	STD_LOGIC; 
             O	:	OUT	STD_LOGIC);
   END COMPONENT;

   ATTRIBUTE BOX_TYPE OF INV : COMPONENT IS "BLACK_BOX";
   COMPONENT OR2
      PORT ( I0	:	IN	STD_LOGIC; 
             I1	:	IN	STD_LOGIC; 
             O	:	OUT	STD_LOGIC);
   END COMPONENT;

   ATTRIBUTE BOX_TYPE OF OR2 : COMPONENT IS "BLACK_BOX";
   COMPONENT OR3
      PORT ( I0	:	IN	STD_LOGIC; 
             I1	:	IN	STD_LOGIC; 
             I2	:	IN	STD_LOGIC; 
             O	:	OUT	STD_LOGIC);
   END COMPONENT;

   ATTRIBUTE BOX_TYPE OF OR3 : COMPONENT IS "BLACK_BOX";
   COMPONENT OR4
      PORT ( I0	:	IN	STD_LOGIC; 
             I1	:	IN	STD_LOGIC; 
             I2	:	IN	STD_LOGIC; 
             I3	:	IN	STD_LOGIC; 
             O	:	OUT	STD_LOGIC);
   END COMPONENT;

   ATTRIBUTE BOX_TYPE OF OR4 : COMPONENT IS "BLACK_BOX";
BEGIN

   XLXI_116 : AND2
      PORT MAP (I0=>EN, I1=>XLXN_199, O=>G);

   XLXI_115 : AND2
      PORT MAP (I0=>EN, I1=>XLXN_197, O=>F);

   XLXI_114 : AND2
      PORT MAP (I0=>EN, I1=>XLXN_195, O=>E);

   XLXI_113 : AND2
      PORT MAP (I0=>EN, I1=>XLXN_193, O=>D);

   XLXI_112 : AND2
      PORT MAP (I0=>EN, I1=>XLXN_201, O=>C);

   XLXI_111 : AND2
      PORT MAP (I0=>EN, I1=>XLXN_189, O=>B);

   XLXI_110 : AND2
      PORT MAP (I0=>EN, I1=>XLXN_187, O=>A);

   XLXI_41 : AND3
      PORT MAP (I0=>XLXN_19, I1=>XLXN_18, I2=>XLXN_17, O=>XLXN_195);

   XLXI_40 : AND3
      PORT MAP (I0=>XLXN_12, I1=>XLXN_11, I2=>XLXN_10, O=>XLXN_201);

   XLXI_42 : AND3
      PORT MAP (I0=>XLXN_26, I1=>XLXN_25, I2=>XLXN_24, O=>XLXN_199);

   XLXI_38 : AND4
      PORT MAP (I0=>XLXN_16, I1=>XLXN_15, I2=>XLXN_14, I3=>XLXN_13,
      O=>XLXN_193);

   XLXI_37 : AND4
      PORT MAP (I0=>XLXN_23, I1=>XLXN_22, I2=>XLXN_21, I3=>XLXN_20,
      O=>XLXN_197);

   XLXI_36 : AND4
      PORT MAP (I0=>XLXN_4, I1=>XLXN_3, I2=>XLXN_2, I3=>XLXN_1, O=>XLXN_187);

   XLXI_39 : AND5
      PORT MAP (I0=>XLXN_9, I1=>XLXN_8, I2=>XLXN_7, I3=>XLXN_6, I4=>XLXN_5,
      O=>XLXN_189);

   XLXI_61 : INV
      PORT MAP (I=>SW1, O=>XLXN_82);

   XLXI_62 : INV
      PORT MAP (I=>SW2, O=>XLXN_79);

   XLXI_63 : INV
      PORT MAP (I=>SW3, O=>XLXN_80);

   XLXI_77 : INV
      PORT MAP (I=>SW3, O=>XLXN_103);

   XLXI_75 : INV
      PORT MAP (I=>SW1, O=>XLXN_102);

   XLXI_74 : INV
      PORT MAP (I=>SW4, O=>XLXN_101);

   XLXI_73 : INV
      PORT MAP (I=>SW3, O=>XLXN_100);

   XLXI_72 : INV
      PORT MAP (I=>SW2, O=>XLXN_99);

   XLXI_71 : INV
      PORT MAP (I=>SW2, O=>XLXN_98);

   XLXI_70 : INV
      PORT MAP (I=>SW4, O=>XLXN_97);

   XLXI_69 : INV
      PORT MAP (I=>SW3, O=>XLXN_92);

   XLXI_68 : INV
      PORT MAP (I=>SW2, O=>XLXN_91);

   XLXI_67 : INV
      PORT MAP (I=>SW1, O=>XLXN_90);

   XLXI_66 : INV
      PORT MAP (I=>SW2, O=>XLXN_94);

   XLXI_65 : INV
      PORT MAP (I=>SW1, O=>XLXN_93);

   XLXI_64 : INV
      PORT MAP (I=>SW3, O=>XLXN_96);

   XLXI_108 : INV
      PORT MAP (I=>SW1, O=>XLXN_171);

   XLXI_94 : INV
      PORT MAP (I=>SW3, O=>XLXN_57);

   XLXI_93 : INV
      PORT MAP (I=>SW2, O=>XLXN_140);

   XLXI_91 : INV
      PORT MAP (I=>SW2, O=>XLXN_134);

   XLXI_90 : INV
      PORT MAP (I=>SW3, O=>XLXN_133);

   XLXI_89 : INV
      PORT MAP (I=>SW4, O=>XLXN_132);

   XLXI_88 : INV
      PORT MAP (I=>SW4, O=>XLXN_128);

   XLXI_87 : INV
      PORT MAP (I=>SW2, O=>XLXN_127);

   XLXI_86 : INV
      PORT MAP (I=>SW1, O=>XLXN_126);

   XLXI_85 : INV
      PORT MAP (I=>SW3, O=>XLXN_122);

   XLXI_84 : INV
      PORT MAP (I=>SW4, O=>XLXN_121);

   XLXI_83 : INV
      PORT MAP (I=>SW3, O=>XLXN_119);

   XLXI_82 : INV
      PORT MAP (I=>SW4, O=>XLXN_117);

   XLXI_81 : INV
      PORT MAP (I=>SW4, O=>XLXN_113);

   XLXI_80 : INV
      PORT MAP (I=>SW1, O=>XLXN_116);

   XLXI_79 : INV
      PORT MAP (I=>SW2, O=>XLXN_111);

   XLXI_78 : INV
      PORT MAP (I=>SW4, O=>XLXN_110);

   XLXI_43 : INV
      PORT MAP (I=>SW4, O=>XLXN_41);

   XLXI_44 : INV
      PORT MAP (I=>SW2, O=>XLXN_47);

   XLXI_45 : INV
      PORT MAP (I=>SW1, O=>XLXN_49);

   XLXI_47 : INV
      PORT MAP (I=>SW4, O=>XLXN_54);

   XLXI_48 : INV
      PORT MAP (I=>SW2, O=>XLXN_51);

   XLXI_49 : INV
      PORT MAP (I=>SW1, O=>XLXN_56);

   XLXI_51 : INV
      PORT MAP (I=>SW4, O=>XLXN_58);

   XLXI_52 : INV
      PORT MAP (I=>SW2, O=>XLXN_73);

   XLXI_53 : INV
      PORT MAP (I=>SW4, O=>XLXN_75);

   XLXI_54 : INV
      PORT MAP (I=>SW1, O=>XLXN_76);

   XLXI_55 : INV
      PORT MAP (I=>SW2, O=>XLXN_77);

   XLXI_56 : INV
      PORT MAP (I=>SW1, O=>XLXN_86);

   XLXI_57 : INV
      PORT MAP (I=>SW3, O=>XLXN_87);

   XLXI_58 : INV
      PORT MAP (I=>SW4, O=>XLXN_89);

   XLXI_59 : INV
      PORT MAP (I=>SW3, O=>XLXN_84);

   XLXI_60 : INV
      PORT MAP (I=>SW2, O=>XLXN_83);

   XLXI_25 : OR2
      PORT MAP (I0=>XLXN_110, I1=>SW1, O=>XLXN_17);

   XLXI_15 : OR3
      PORT MAP (I0=>SW4, I1=>XLXN_80, I2=>XLXN_79, O=>XLXN_7);

   XLXI_16 : OR3
      PORT MAP (I0=>XLXN_84, I1=>XLXN_83, I2=>XLXN_82, O=>XLXN_8);

   XLXI_17 : OR3
      PORT MAP (I0=>XLXN_89, I1=>XLXN_87, I2=>XLXN_86, O=>XLXN_9);

   XLXI_20 : OR3
      PORT MAP (I0=>XLXN_92, I1=>XLXN_91, I2=>XLXN_90, O=>XLXN_12);

   XLXI_21 : OR3
      PORT MAP (I0=>XLXN_97, I1=>SW3, I2=>SW2, O=>XLXN_13);

   XLXI_23 : OR3
      PORT MAP (I0=>XLXN_101, I1=>XLXN_100, I2=>XLXN_99, O=>XLXN_15);

   XLXI_26 : OR3
      PORT MAP (I0=>SW3, I1=>XLXN_111, I2=>SW1, O=>XLXN_18);

   XLXI_28 : OR3
      PORT MAP (I0=>XLXN_117, I1=>SW2, I2=>SW1, O=>XLXN_20);

   XLXI_29 : OR3
      PORT MAP (I0=>XLXN_119, I1=>SW2, I2=>SW1, O=>XLXN_21);

   XLXI_30 : OR3
      PORT MAP (I0=>XLXN_121, I1=>XLXN_122, I2=>SW1, O=>XLXN_22);

   XLXI_32 : OR3
      PORT MAP (I0=>SW3, I1=>SW2, I2=>SW1, O=>XLXN_24);

   XLXI_9 : OR4
      PORT MAP (I0=>XLXN_41, I1=>SW3, I2=>SW2, I3=>SW1, O=>XLXN_1);

   XLXI_10 : OR4
      PORT MAP (I0=>SW4, I1=>SW3, I2=>XLXN_47, I3=>SW1, O=>XLXN_2);

   XLXI_11 : OR4
      PORT MAP (I0=>XLXN_54, I1=>SW3, I2=>XLXN_51, I3=>XLXN_49, O=>XLXN_3);

   XLXI_12 : OR4
      PORT MAP (I0=>XLXN_58, I1=>XLXN_57, I2=>SW2, I3=>XLXN_56, O=>XLXN_4);

   XLXI_13 : OR4
      PORT MAP (I0=>XLXN_75, I1=>SW3, I2=>XLXN_73, I3=>SW1, O=>XLXN_5);

   XLXI_14 : OR4
      PORT MAP (I0=>SW4, I1=>SW3, I2=>XLXN_77, I3=>XLXN_76, O=>XLXN_6);

   XLXI_22 : OR4
      PORT MAP (I0=>SW4, I1=>SW3, I2=>XLXN_98, I3=>SW1, O=>XLXN_14);

   XLXI_33 : OR4
      PORT MAP (I0=>XLXN_132, I1=>XLXN_133, I2=>XLXN_134, I3=>SW1, O=>XLXN_25);

   XLXI_95 : OR4
      PORT MAP (I0=>SW4, I1=>SW3, I2=>XLXN_140, I3=>XLXN_171, O=>XLXN_26);

   XLXI_18 : OR4
      PORT MAP (I0=>SW4, I1=>XLXN_96, I2=>SW2, I3=>SW1, O=>XLXN_10);

   XLXI_19 : OR4
      PORT MAP (I0=>SW4, I1=>SW3, I2=>XLXN_94, I3=>XLXN_93, O=>XLXN_11);

   XLXI_31 : OR4
      PORT MAP (I0=>XLXN_128, I1=>SW3, I2=>XLXN_127, I3=>XLXN_126, O=>XLXN_23);

   XLXI_24 : OR4
      PORT MAP (I0=>SW4, I1=>XLXN_103, I2=>SW2, I3=>XLXN_102, O=>XLXN_16);

   XLXI_27 : OR4
      PORT MAP (I0=>XLXN_113, I1=>SW3, I2=>SW2, I3=>XLXN_116, O=>XLXN_19);

END SCHEMATIC;



